export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_ERROR: "LOGOUT_ERROR",
    PAYMENT_REQUEST: "PAYMENT_REQUEST",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_ERROR: "PAYMENT_ERROR",
    TIME_REQUEST: "TIME_REQUEST",
    TIME_SUCCESS: "TIME_SUCCESS",
    TIME_ERROR: "TIME_ERROR",
}