export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_ERROR: "LOGOUT_ERROR",
    ADMIN_REGISTER_REQUEST: "ADMIN_REGISTER_REQUEST",
    ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
    ADMIN_REGISTER_ERROR: "ADMIN_REGISTER_ERROR",
    MEMBER_REGISTER_REQUEST: "MEMBER_REGISTER_REQUEST",
    MEMBER_REGISTER_SUCCESS: "MEMBER_REGISTER_SUCCESS",
    MEMBER_REGISTER_ERROR: "MEMBER_REGISTER_ERROR",
}
